export const ActionTypes = {
    SET_PARAMETER_TEMPLATES:  "SET_PARAMETER_TEMPLATES",
    SELECTED_PARAMETER_TEMPLATE: "SELECTED_PARAMETER_TEMPLATE",
    REMOVE_SELECTED_PARAMETER_TEMPLATE: "REMOVE_SELECTED_PARAMETER_TEMPLATE",
    SET_INTERFACE_SETUPS:  "SET_INTERFACE_SETUPS",
    SELECTED_INTERFACE_SETUP: "SELECTED_INTERFACE_SETUP",
    REMOVE_SELECTED_INTERFACE_SETUP: "REMOVE_SELECTED_INTERFACE_SETUP",
}