import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios';

export const getSuccessFactors = createAsyncThunk('getSuccessFactors', async () => {
    const response = await axios.get('/api/SuccessFactors');
    const data = await response.data;
    return data;
});

const successFactorsSlice = createSlice({
    name: 'successFactors',
    initialState: [
        {
            id: '1',
            globalEmployeeId: '5003078',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Lio',
            middleName: 'GPS',
            lastName: 'Messi',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false, expanded: false
        },
        {
            id: '2',
            globalEmployeeId: '5003079',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Cristiano',
            middleName: 'GPS',
            lastName: 'Ronaldo',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '3',
            globalEmployeeId: '5003080',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Mo',
            middleName: 'GPS',
            lastName: 'Salah',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '4',
            globalEmployeeId: '5003081',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Erling',
            middleName: 'GPS',
            lastName: 'Haland',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '5',
            globalEmployeeId: '5003082',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Kylian',
            middleName: 'GPS',
            lastName: 'Mbappe',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '6',
            globalEmployeeId: '5003083',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Miguel',
            middleName: 'GPS',
            lastName: 'Almiron',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '7',
            globalEmployeeId: '5003087',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Miguel',
            middleName: 'GPS',
            lastName: 'Almiron',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '1',
            globalEmployeeId: '5003078',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Lio',
            middleName: 'GPS',
            lastName: 'Messi',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '2',
            globalEmployeeId: '5003079',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Cristiano',
            middleName: 'GPS',
            lastName: 'Ronaldo',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '3',
            globalEmployeeId: '5003080',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Mo',
            middleName: 'GPS',
            lastName: 'Salah',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '4',
            globalEmployeeId: '5003081',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Erling',
            middleName: 'GPS',
            lastName: 'Haland',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '5',
            globalEmployeeId: '5003082',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Kylian',
            middleName: 'GPS',
            lastName: 'Mbappe',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '6',
            globalEmployeeId: '5003083',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Miguel',
            middleName: 'GPS',
            lastName: 'Almiron',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '7',
            globalEmployeeId: '5003087',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Miguel',
            middleName: 'GPS',
            lastName: 'Almiron',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '1',
            globalEmployeeId: '5003078',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Lio',
            middleName: 'GPS',
            lastName: 'Messi',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '2',
            globalEmployeeId: '5003079',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Cristiano',
            middleName: 'GPS',
            lastName: 'Ronaldo',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '3',
            globalEmployeeId: '5003080',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Mo',
            middleName: 'GPS',
            lastName: 'Salah',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '4',
            globalEmployeeId: '5003081',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Erling',
            middleName: 'GPS',
            lastName: 'Haland',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '5',
            globalEmployeeId: '5003082',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Kylian',
            middleName: 'GPS',
            lastName: 'Mbappe',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '6',
            globalEmployeeId: '5003083',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Miguel',
            middleName: 'GPS',
            lastName: 'Almiron',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        },
        {
            id: '7',
            globalEmployeeId: '5003087',
            activityType: 'P3',
            annualSalary: '123561',
            annualWorkingHours: '2080',
            birthDate: '1987-11-24 00:00:00.000000',
            ccServiceAreaDescription: 'Cyber & Strategic Risk',
            ccServiceLine: 'A58',
            ccServiceLineDescription: 'Cyber Infraestructure',
            citizenshipCountryOfBirth: 'USA',
            citizenshipNationality: 'USA',
            companyCode: '1000',
            companyCodeDesc: 'Deloitte & Touche LLP',
            costCenter: '100060145',
            costCenterOfficeCode: '243',
            costCenterOfficeDesc: 'FEDERAL',
            costCenterRegion: 'GPS Hybrid',
            costCenterRegionDesc: 'Operate Tech Assets',
            countryGrouping: 'US',
            directorsYn: 'N',
            eeGroup: 'Standard',
            eeGroupCode: 'EC1',
            emailId: 'aaaa@bc.com',
            employeeStatusCode: 'A',
            employeeStatusCodeDescription: 'Active',
            employeeSubGroupCode: 'ET3',
            federalStatus: 'B',
            firstName: 'Miguel',
            middleName: 'GPS',
            lastName: 'Almiron',
            indicatorPartTimeEmployee: '1',
            jobDescription: 'Consultan 1, HC / HR Strat COM HC HRT SAP/SF Enabler',
            jobKey: '',
            managerId: '50000024',
            partnerYn: 'N',
            payrollArea: 'ZB',
            payScaleArea: 'A',
            payScaleGroup: 'P3',
            personnelArea: 'USA-Baltimore',
            personnelNumber: '50003078',
            phoneDesk: '(187)699-8222',
            phoneOffice: '(187)699-8222',
            preferredContract: '(187)699-8222',
            sapLegacyPersonId: '5618233',
            sapLegacypersonnelNumber: '5003078',
            serviceArea: '115',
            standardHours: '40',
            suffix: 'SU4',
            textfield: 'RISK AND FINANCIAL ADVISORY',
            waers: 'USD', expanded: false
        }
    ],
    reducers: {},
    extraReducers: {
        //[getSuccessFactors.fulfilled]: (state, action) => action.payload,
    },
});

export default successFactorsSlice.reducer;